# Generated by Django 3.2.7 on 2022-02-25 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_time', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('exit_time', django_jalali.db.models.jDateTimeField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enterexit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Enter Exit',
            },
        ),
    ]
