# Generated by Django 3.2.7 on 2022-03-14 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_time', django_jalali.db.models.jDateTimeField(blank=True, null=True)),
                ('exit_time', django_jalali.db.models.jDateTimeField(blank=True, null=True)),
                ('work_time', models.DurationField(blank=True, default=None, null=True)),
                ('date', django_jalali.db.models.jDateField(default='1400-12-07')),
                ('role', models.CharField(choices=[('STAFF', 'STAFF'), ('TEACHER', 'TEACHER')], default='STAFF', max_length=7)),
                ('is_paid', models.BooleanField(default=False)),
                ('done_percent_goal', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enterexit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Enter Exit',
            },
        ),
    ]
