# Generated by Django 3.2.7 on 2022-02-27 08:31

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterexit',
            name='date',
            field=django_jalali.db.models.jDateField(default='1400-12-07'),
        ),
    ]
