# Generated by Django 3.2.7 on 2022-02-25 16:24

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterexit',
            name='exit_time',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True),
        ),
    ]
