# Generated by Django 3.2.7 on 2022-02-28 09:15

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlog', '0002_enterexit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterexit',
            name='work_time',
            field=models.DurationField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='enterexit',
            name='enter_time',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True),
        ),
    ]
