# Generated by Django 3.2.7 on 2022-02-25 16:27

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlog', '0002_alter_enterexit_exit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterexit',
            name='work_time',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True),
        ),
    ]
