# Generated by Django 3.2.7 on 2022-02-25 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventlog', '0003_enterexit_work_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterexit',
            name='work_time',
        ),
    ]
