# Generated by Django 3.2.7 on 2022-02-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlog', '0003_auto_20220228_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterexit',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
