# Generated by Django 3.2.7 on 2022-03-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlog', '0005_enterexit_done_percent_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterexit',
            name='done_percent_goal',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
