# Generated by Django 3.2.7 on 2022-03-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlog', '0006_alter_enterexit_done_percent_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterexit',
            name='role',
            field=models.CharField(choices=[('STAFF', 'STAFF'), ('TEACHER', 'TEACHER')], default='STAFF', max_length=7),
        ),
    ]
