# Generated by Django 3.2.7 on 2022-02-28 10:50

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20220228_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_joined',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
