# Generated by Django 3.2.7 on 2022-02-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_profile_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hourl_wage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
