# Generated by Django 3.2.7 on 2022-03-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_profile_hourl_wage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryreceipt',
            name='total_hours',
            field=models.IntegerField(),
        ),
    ]
