# Generated by Django 3.2.7 on 2022-03-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_rename_hourl_wage_profile_hourly_wage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='employee_code',
            field=models.IntegerField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hourly_wage',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
