# Generated by Django 3.2.7 on 2022-03-02 07:53

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20220302_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_joined',
            field=django_jalali.db.models.jDateTimeField(editable=False),
        ),
    ]
