# Generated by Django 3.2.7 on 2022-03-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_profile_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hourly_wage',
        ),
        migrations.AddField(
            model_name='salaryreceipt',
            name='hourly_wage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
