# Generated by Django 3.2.7 on 2022-03-02 09:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0014_auto_20220302_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryreceipt',
            name='hourly_wage',
        ),
        migrations.AddField(
            model_name='profile',
            name='hourly_wage',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='salaryreceipt',
            name='employee_code',
            field=models.IntegerField(default=23444),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salaryreceipt',
            name='payment_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2022, 3, 2)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salaryreceipt',
            name='salary',
            field=models.FloatField(default=450000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salaryreceipt',
            name='total_hours',
            field=models.FloatField(default=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salaryreceipt',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
