# Generated by Django 3.2.7 on 2022-03-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20220302_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hourly_wage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
