# Generated by Django 3.2.7 on 2022-03-02 10:29

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_profile_hourly_wage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salaryreceipt',
            old_name='payment_date',
            new_name='from_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hourly_wage',
        ),
        migrations.AddField(
            model_name='salaryreceipt',
            name='hourly_wage',
            field=models.IntegerField(default=45000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salaryreceipt',
            name='to_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2022, 3, 2)),
            preserve_default=False,
        ),
    ]
