# Generated by Django 3.2.7 on 2022-03-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20220302_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryreceipt',
            name='employee_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salaryreceipt',
            name='salary',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salaryreceipt',
            name='total_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
