# Generated by Django 3.2.7 on 2022-03-03 14:18

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_profile_employee_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_joined',
            field=django_jalali.db.models.jDateTimeField(),
        ),
    ]
