# Generated by Django 3.2.7 on 2022-03-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20220307_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('BOSS', 'BOSS'), ('MANAGER', 'MANAGER'), ('SUPERVISOR', 'SUPERVISOR'), ('STAFF', 'STAFF'), ('TEACHER', 'TEACHER'), ('FREELANCER', 'FREELANCER'), ('ADMIN', 'ADMIN'), ('INTERN', 'INTERN')], default='STAFF', max_length=10),
        ),
    ]
