# Generated by Django 3.2.7 on 2022-03-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_alter_salaryreceipt_hourly_wage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='which_group',
            field=models.CharField(choices=[('BOSS', 'BOSS'), ('MANAGER', 'MANAGER'), ('SUPERVISOR', 'SUPERVISOR'), ('STAFF', 'STAFF'), ('ADMIN', 'ADMIN'), ('TEACHER', 'TEACHER'), ('INTERN', 'INTERN'), ('FREELANCER', 'FREELANCER'), ('ALL', 'ALL')], default='ALL', max_length=16),
        ),
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, to='account.Group'),
        ),
    ]
