# Generated by Django 3.2.7 on 2022-03-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_auto_20220309_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notification',
            field=models.ManyToManyField(blank=True, to='account.Notification'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='which_group',
            field=models.CharField(choices=[('BOSS', 'BOSS'), ('MANAGER', 'MANAGER'), ('SUPERVISOR', 'SUPERVISOR'), ('STAFF', 'STAFF'), ('ADMIN', 'ADMIN'), ('TEACHER', 'TEACHER'), ('INTERN', 'INTERN'), ('FREELANCER', 'FREELANCER'), ('ALL', 'ALL'), ('WEB', 'WEB'), ('GRAPHIC', 'GRAPHIC'), ('CONTENT_PRODUCTION', 'CONTENT_PRODUCTION')], default='ALL', max_length=18),
        ),
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.ManyToManyField(blank=True, to='account.Group'),
        ),
    ]
