# Generated by Django 3.2.7 on 2022-03-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_auto_20220309_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='notification',
        ),
        migrations.AddField(
            model_name='profile',
            name='notification_body',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='notification_title',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
