# Generated by Django 3.2.7 on 2022-03-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_auto_20220309_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='notification_body',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='notification_title',
        ),
        migrations.AddField(
            model_name='profile',
            name='notification_title',
            field=models.ManyToManyField(to='account.Notification'),
        ),
    ]
