# Generated by Django 3.2.7 on 2022-03-09 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_auto_20220309_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='notification_title',
            new_name='notification',
        ),
    ]
