# Generated by Django 3.2.7 on 2022-03-09 11:54

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_rename_notification_title_profile_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='expiration',
            field=django_jalali.db.models.jDateTimeField(),
        ),
    ]
