# Generated by Django 3.2.7 on 2022-03-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_alter_notification_expiration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='Announcement',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='notification',
        ),
        migrations.AddField(
            model_name='profile',
            name='announcement',
            field=models.ManyToManyField(to='account.Announcement'),
        ),
        migrations.DeleteModel(
            name='WorkLeave',
        ),
    ]
