# Generated by Django 3.2.7 on 2022-03-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_alter_announcement_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='seen',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='which_group',
        ),
        migrations.AddField(
            model_name='announcement',
            name='role',
            field=models.CharField(choices=[('BOSS', 'BOSS'), ('MANAGER', 'MANAGER'), ('SUPERVISOR', 'SUPERVISOR'), ('STAFF', 'STAFF')], default='BOSS', max_length=18),
        ),
    ]
