# Generated by Django 3.2.7 on 2022-03-13 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_auto_20220313_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='group',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='account.group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='announcement',
            field=models.ManyToManyField(blank=True, to='account.Announcement'),
        ),
    ]
