# Generated by Django 3.2.7 on 2022-03-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_auto_20220313_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='group',
        ),
        migrations.AddField(
            model_name='announcement',
            name='group',
            field=models.ManyToManyField(blank=True, to='account.Group'),
        ),
    ]
