# Generated by Django 3.2.7 on 2022-03-13 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0042_auto_20220313_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='role',
        ),
    ]
