# Generated by Django 3.2.7 on 2022-03-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0043_remove_announcement_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='role',
            field=models.CharField(choices=[('BOSS', 'BOSS'), ('MANAGER', 'MANAGER'), ('SUPERVISOR', 'SUPERVISOR'), ('STAFF', 'STAFF')], default='BOSS', max_length=18),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('BOSS', 'BOSS'), ('MANAGER', 'MANAGER'), ('SUPERVISOR', 'SUPERVISOR'), ('STAFF', 'STAFF'), ('TEACHER', 'TEACHER'), ('FREELANCER', 'FREELANCER'), ('ADMIN', 'ADMIN'), ('INTERN', 'INTERN')], default='STAFF', max_length=10),
        ),
    ]
