# Generated by Django 3.2.7 on 2022-03-13 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0044_auto_20220313_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='group',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='role',
        ),
    ]
