# Generated by Django 3.2.7 on 2022-03-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0046_auto_20220313_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='role',
            new_name='first_role',
        ),
        migrations.AddField(
            model_name='profile',
            name='second_role',
            field=models.CharField(blank=True, choices=[('BOSS', 'BOSS'), ('MANAGER', 'MANAGER'), ('SUPERVISOR', 'SUPERVISOR'), ('STAFF', 'STAFF'), ('TEACHER', 'TEACHER'), ('FREELANCER', 'FREELANCER'), ('ADMIN', 'ADMIN'), ('INTERN', 'INTERN')], default='STAFF', max_length=10, null=True),
        ),
    ]
