# Generated by Django 3.2.7 on 2022-02-23 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=255)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EnterExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_time', models.TimeField()),
                ('exit_time', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enterexit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyPlanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'BOSS'), (2, 'MANAGER'), (3, 'SUPERVISOR'), (4, 'STAFF')], default=4)),
                ('today_goal', models.TextField()),
                ('inspiration', models.TextField()),
                ('education_title', models.CharField(max_length=128)),
                ('education_time', models.TimeField()),
                ('break_fast_time', models.TimeField()),
                ('lunch_time', models.TimeField()),
                ('gaming_time', models.TimeField()),
                ('drink', models.PositiveSmallIntegerField(default=0)),
                ('mind_dump', models.TextField()),
                ('date', django_jalali.db.models.jDateField(auto_now=True)),
                ('what_day', models.PositiveSmallIntegerField(choices=[(1, 'SAT'), (2, 'SUN'), (3, 'MON'), (6, 'TUE'), (5, 'WED'), (6, 'THU'), (7, 'FRI')], default=1)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan', to='planner.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
