# Generated by Django 3.2.7 on 2022-02-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyplanner',
            name='break_fast_time',
        ),
        migrations.AddField(
            model_name='dailyplanner',
            name='breakfast_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyplanner',
            name='education_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyplanner',
            name='education_title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='dailyplanner',
            name='gaming_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyplanner',
            name='inspiration',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyplanner',
            name='lunch_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyplanner',
            name='mind_dump',
            field=models.TextField(blank=True, null=True),
        ),
    ]
