# Generated by Django 3.2.7 on 2022-02-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_auto_20220225_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyplanner',
            name='role',
            field=models.CharField(choices=[('BOSS', 'BOSS'), ('MANAGER', 'MANAGER'), ('SUPERVISOR', 'SUPERVISOR'), ('STAFF', 'STAFF')], default=('STAFF', 'STAFF'), max_length=10),
        ),
        migrations.AlterField(
            model_name='dailyplanner',
            name='what_day',
            field=models.CharField(choices=[('SAT', 'SAT'), ('SUN', 'SUN'), ('MON', 'MON'), ('THU', 'TUE'), ('WED', 'WED'), ('THU', 'THU'), ('FRI', 'FRI')], default=('SAT', 'SAT'), max_length=3),
        ),
    ]
