# Generated by Django 3.2.7 on 2022-03-07 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planner', '0003_auto_20220227_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyplanner',
            name='role',
        ),
        migrations.AddField(
            model_name='todaygoal',
            name='done_percent',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('date', django_jalali.db.models.jDateField()),
                ('daily_planner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.dailyplanner')),
                ('feedback_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacker', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbackee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
