# Generated by Django 3.2.7 on 2022-02-26 07:47

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='date',
            field=django_jalali.db.models.jDateField(auto_now=True),
        ),
    ]
