# Generated by Django 3.2.7 on 2022-03-07 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_auto_20220307_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todaygoal',
            name='done_percent',
        ),
    ]
