# Generated by Django 3.2.7 on 2022-02-26 07:59

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_subtask_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='date',
            field=django_jalali.db.models.jDateField(default='1400:12:06'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=django_jalali.db.models.jDateField(default='1400:12:06'),
        ),
    ]
