# Generated by Django 3.2.7 on 2022-02-25 07:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_alter_dailyplanner_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyplanner',
            name='drink',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
