# Generated by Django 3.2.7 on 2022-02-26 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planner', '0007_auto_20220226_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.DurationField(),
        ),
        migrations.CreateModel(
            name='TodayGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_goal', models.CharField(max_length=128)),
                ('date', django_jalali.db.models.jDateField(default='1400-12-07')),
                ('done', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
