# Generated by Django 3.2.7 on 2022-02-26 11:55

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_alter_dailyplanner_today_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.date(2022, 2, 26)),
        ),
        migrations.AlterField(
            model_name='todaygoal',
            name='date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2022, 2, 26)),
        ),
    ]
